### ISSUE TITLE
scheme used to search target, not scheme

### ISSUE THREAD

**Issue by lukaswuerzburger** [lyndsey-ferguson/get_product_bundle_id#1]
https://github.com/lyndsey-ferguson/get_product_bundle_id/blob/92fd9f75311706a9a10cd7767fde9605b240aac4/lib/fastlane/plugin/get_product_bundle_id/actions/get_product_bundle_id_action.rb#L9

The `scheme` parameter is used to look up a target by name. When creating a target, a scheme is automatically created with the same name. However, a scheme can be renamed and wouldn't match anymore with the target name.

**Comment by lyndsey-ferguson** [comment]
Sorry @lukaswuerzburger I didn't get an alert about this issue. I cannot look at it this moment, but it will be on my list.

**Comment by lyndsey-ferguson** [comment]
Fixed in [v0.1.3](https://github.com/lyndsey-ferguson/get_product_bundle_id/releases/tag/v0.1.3)
